# -*- coding: utf-8 -*-
"""Visulizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZpWsGEgVL7FwsdUJcwJMv8xrvOfBO9F3
"""

import pandas as pd
import matplotlib.pyplot as plt


class SalesDataAnalyzer:

    def __init__(self):
        self.df = None


    def load_dataset(self):

        print("\n== Load Dataset ==")

        data = {
            "SalesID": [ 101, 102, 103, 104, 105,  ],

            "Product": ["Product A", "Product B", "Product C","Product D", "Product E"],

            "Region": ["North", "East", "West", "South", "Central"],

            "Sales": [500, 600, 700, 800, 550],

            "Year": [2022, 2022, 2022, 2022, 2022]
        }

        self.df = pd.DataFrame(data)

        print("Dataset loaded successfully!")

        print("\nDataset:")
        print(self.df)


    def get_column(self, column_name):

        for column in self.df.columns:

            if column.lower() == column_name.lower():

                return column

        return None


    def explore_data(self):

        if self.df is None:

            print("Please load the dataset first!")

            return

        print("\n== Explore Data ==")

        print("1. Display the first 5 rows")
        print("2. Display the last 5 rows")
        print("3. Display column names")
        print("4. Display data types")
        print("5. Display basic information")

        choice = int(input("Enter your choice: "))

        if choice == 1:

            print("\nFirst 5 Rows:")
            print(self.df.head())

        elif choice == 2:

            print("\nLast 5 Rows:")
            print(self.df.tail())

        elif choice == 3:

            print("\nColumn Names:")
            print(self.df.columns.tolist())

        elif choice == 4:

            print("\nData Types:")
            print(self.df.dtypes)

        elif choice == 5:

            print("\nBasic Information:")
            self.df.info()

        else:

            print("Invalid choice!")


    def dataframe_operations(self):

        if self.df is None:

            print("Please load the dataset first!")

            return

        print("\n== DataFrame Operations ==")

        print("1. Sort data")
        print("2. Filter data")
        print("3. Group data by Region")
        print("4. Group data by Product")

        choice = int(input("Enter your choice: "))

        if choice == 1:

            column_name = input("Enter column name to sort by: ")

            column = self.get_column(column_name)

            if column:

                print("\nSorted Data:")
                print(self.df.sort_values(by=column))

            else:

                print("Column not found!")


        elif choice == 2:

            column_name = input("Enter column name: ")

            column = self.get_column(column_name)

            if column:

                value = input("Enter value to filter: ")

                result = self.df[
                    self.df[column].astype(str).str.lower()
                    == value.lower()
                ]

                print("\nFiltered Data:")
                print(result)

            else:

                print("Column not found!")

        elif choice == 3:

            print("\nSales by Region:")

            result = self.df.groupby(
                "Region"
            )["Sales"].sum()

            print(result)

        elif choice == 4:

            print("\nSales by Product:")

            result = self.df.groupby(
                "Product"
            )["Sales"].sum()

            print(result)

        else:

            print("Invalid choice!")

    def handle_missing_data(self):

        if self.df is None:

            print("Please load the dataset first!")

            return

        print("\n== Handle Missing Data ==")

        print("1. Display rows with missing values")
        print("2. Fill missing values with mean")
        print("3. Drop rows with missing values")
        print("4. Replace missing values with a specific value")

        choice = int(input("Enter your choice: "))

        if choice == 1:

            missing_rows = self.df[
                self.df.isnull().any(axis=1)
            ]

            if missing_rows.empty:

                print( "\nNo missing values found in the dataset!")

            else:

                print(missing_rows)

        elif choice == 2:

            numeric_columns = self.df.select_dtypes(
                include="number"
            ).columns

            for column in numeric_columns:

                self.df[column] = self.df[column].fillna(
                    self.df[column].mean()
                )

            print("Missing values filled with mean successfully!")

        elif choice == 3:

            self.df.dropna(inplace=True)

            print("Rows with missing values dropped successfully!")

        elif choice == 4:

            value = input("Enter the value to replace missing values: ")

            self.df.fillna(
                value,
                inplace=True
            )

            print("Missing values replaced successfully!")

        else:

            print("Invalid choice!")

    def descriptive_statistics(self):

        if self.df is None:

            print("Please load the dataset first!")

            return

        print("\n== Descriptive Statistics ==")

        print(self.df.describe())

    def visualization(self):

        if self.df is None:

            print("Please load the dataset first!")

            return

        print("\n== Data Visualization ==")

        print("1. Bar Plot")
        print("2. Line Plot")
        print("3. Scatter Plot")
        print("4. Pie Chart")
        print("5. Histogram")
        print("6. Stack Plot")

        choice = int(input("Enter your choice: "))

        if choice == 1:

            print("\n== Bar Plot ==")

            x_name = input("Enter x-axis column name: ")

            y_name = input("Enter y-axis column name: ")

            x = self.get_column(x_name)
            y = self.get_column(y_name)

            if x and y:

                print("Generating bar plot...")

                plt.figure()

                plt.bar(
                    self.df[x],
                    self.df[y]
                )

                plt.xlabel(x)
                plt.ylabel(y)

                plt.title("Bar Plot")

                plt.xticks(rotation=45)

                plt.tight_layout()

                plt.show()

                print("Bar plot displayed successfully!")

            else:

                print("Column not found!")


        elif choice == 2:

            print("\n== Line Plot ==")

            x_name = input("Enter x-axis column name: ")

            y_name = input("Enter y-axis column name: ")

            x = self.get_column(x_name)
            y = self.get_column(y_name)

            if x and y:

                print("Generating line plot...")

                plt.figure()

                plt.plot(
                    self.df[x],
                    self.df[y],
                    marker="o"
                )

                plt.xlabel(x)
                plt.ylabel(y)

                plt.title("Line Plot")

                plt.tight_layout()

                plt.show()

                print("Line plot displayed successfully!")

            else:

                print("Column not found!")


        elif choice == 3:

            print("\n== Scatter Plot ==")

            print("Available columns:",list(self.df.columns))

            x_name = input("Enter x-axis column name: ")

            y_name = input("Enter y-axis column name: ")

            x = self.get_column(x_name)
            y = self.get_column(y_name)

            if x and y:

                print("Generating scatter plot...")

                plt.figure()

                plt.scatter(
                    self.df[x],
                    self.df[y]
                )

                plt.xlabel(x)
                plt.ylabel(y)

                plt.title("Scatter Plot")

                plt.grid(True)

                plt.tight_layout()

                plt.show()

                print("Scatter plot displayed successfully!")

            else:

                print("Column not found!")

                print("Available columns:",list(self.df.columns))


        elif choice == 4:

            print("\n== Pie Chart ==")

            column_name = input("Enter column name: ")

            column = self.get_column(column_name)

            if column:

                values = self.df[
                    column
                ].value_counts()

                plt.figure()

                plt.pie(
                    values,
                    labels=values.index,
                    autopct="%1.1f%%"
                )

                plt.title("Pie Chart")

                plt.show()

                print("Pie chart displayed successfully!")

            else:

                print("Column not found!")


        elif choice == 5:

            print("\n== Histogram ==")

            column_name = input("Enter column name: ")

            column = self.get_column(column_name)

            if column:

                print("Generating histogram...")

                plt.figure()

                plt.hist(
                    self.df[column],
                    bins=5
                )

                plt.xlabel(column)
                plt.ylabel("Frequency")

                plt.title("Histogram")

                plt.show()

                print("Histogram displayed successfully!")

            else:

                print("Column not found!")


        elif choice == 6:

            print("\n== Stack Plot ==")

            col1_name = input("Enter first column: ")

            col2_name = input("Enter second column: ")


            col3_name = input("Enter third column: ")

            col1 = self.get_column(col1_name)
            col2 = self.get_column(col2_name)
            col3 = self.get_column(col3_name)

            if col1 and col2 and col3:

                print("Generating stack plot...")

                plt.figure()

                plt.stackplot(
                    range(len(self.df)),
                    self.df[col1],
                    self.df[col2],
                    self.df[col3],
                    labels=[
                        col1,
                        col2,
                        col3
                    ]
                )

                plt.xlabel("Records")

                plt.ylabel("Values")

                plt.title("Stack Plot")

                plt.legend()

                plt.show()

                print("Stack plot displayed successfully!")

            else:

                print("Column not found!")

        else:

            print("Invalid choice!")


    def save_visualization(self):

        print("\n== Save Visualization ==")

        filename = input("Enter file name to save the plot "
        "(e.g., scatter_plot.png): "
        )

        try:

            plt.savefig(filename)

            print(
                f"Visualization saved as "
                f"{filename} successfully!"
            )

        except Exception as e:

            print("Error saving visualization:",e)


    def run(self):

        while True:

            print("\n========== Data Analysis & Visualization Program ==========")

            print("Please select an option:")

            print("1. Load Dataset")

            print("2. Explore Data")

            print("3. Perform DataFrame Operations")

            print("4. Handle Missing Data")

            print("5. Generate Descriptive Statistics")

            print("6. Data Visualization")

            print("7. Save Visualization")

            print("8. Exit")

            print("============================================================")

            choice = int(input("\nEnter your choice: "))

            if choice == 1:

                self.load_dataset()

            elif choice == 2:

                self.explore_data()

            elif choice == 3:

                self.dataframe_operations()

            elif choice == 4:

                self.handle_missing_data()

            elif choice == 5:

                self.descriptive_statistics()

            elif choice == 6:

                self.visualization()

            elif choice == 7:

                self.save_visualization()

            elif choice == 8:

                print("\nExiting the program. Goodbye!")

                break

            else:

                print("Invalid choice! Please try again.")


if __name__ == "__main__":

    analyzer = SalesDataAnalyzer()

    analyzer.run()